### ISSUE TITLE
view 与 viewModel 的绑定在哪里？

### ISSUE THREAD

**Issue by expkzb** [shenAlexy/MVVM#2]
你可以试试 RZDataBinding ，通过声明 数据源代理 及 KVO 的方式
形如：`[view setViewModel:viewModel]` 而非现在的 `[view setData:data]`
另外网络层的封装也不够，简单来说，移植到另一个项目时，你不光要复制网络请求，还要复制viewModel层，因为你将JSONModel的映射放在了viewModel里

**Comment by longhongwei17** [comment]
标示 完全没看懂 哈哈哈

**Comment by shenAlexy** [comment]
刚开始学习MVVM，谢谢支持
